### ISSUE TITLE
api: define how to re-run task over time range

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/platform#611]
We have an endpoint to retry a single run: https://github.com/influxdata/platform/blob/6a861f2648a3a52da9f022bb892a29ba98d72a74/http/swagger.yml#L855-L885

But we don't yet have an endpoint that says "re-run this task over the time range [start, end]". We need that endpoint to support manual re-runs of a task for a known backfilled time range.

**Comment by docmerlin** [comment]
I was thinking something like:
```yaml
  '/tasks/{taskId}/runs/{begin}/{end}/retry':
    post:
      tags:
        - Tasks
      summary: Retry a task run on interval [begin, end)
      parameters:
        - in: path
          name: taskId
          schema:
            type: string
          required: true
          description: task ID
        - in: path
          name: begin
          schema:
            type: string
            format: date-time
          required: true
          description: beginning of retry interval
        - in: path
          name: end
          schema:
            type: string
            format: date-time
          required: true
          description: ending of retry interval
```
